sudo: required

services:
  - docker

language: ruby

rvm:
  - 2.1.3
addons:
  firefox: "38.0.5" 

before_install:
  - docker build -t demo_image .
  - docker run -d --name test_container -p 127.0.0.1:80:4567 demo_image
  - docker ps -a
  - sudo docker exec test_container bin/rspec spec
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"